dist: trusty
sudo: required

language: node_js
env: NODE_ENV=production
node_js:
  - "6"
  - "7"
  - "8"

script:
# install additional testing dependencies
- npm install --only=development
- npm run eslint
- npm run build
- npm run test

jobs:
  include:
    - stage: deploy
      script:
        - npm run build
      deploy:
        - provider: pages
          node_js: "8"
          local_dir: dist
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          on:
            branch: master
        - provider: gcs
          node_js: "8"
          local_dir: dist
          skip_cleanup: true
          access_key_id: $GCS_ACCESS_ID
          secret_access_key: $GCS_SECRET_KEY
          bucket: $GCS_BUCKET
          detect_encoding: true
          acl: public-read
          on:
            branch: master
