language: node_js
node_js:
  - "6"
  - "7"
  - "8"
script:
  - npm run build
  - npm run test
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
