dist: trusty
sudo: required

language: node_js
env: NODE_ENV=test
node_js:
  - "6"
  - "7"
  - "8"
cache: yarn

script:
- yarn install
- yarn eslint
- yarn build
- yarn test

jobs:
  include:
    - stage: deploy
      script:
        - yarn build
      deploy:
        - provider: pages
          env: NODE_ENV=production
          node_js: "8"
          local_dir: dist
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          on:
            branch: master
        - provider: gcs
          env: NODE_ENV=production
          node_js: "8"
          local_dir: dist
          skip_cleanup: true
          access_key_id: $GCS_ACCESS_ID
          secret_access_key: $GCS_SECRET_KEY
          bucket: $GCS_BUCKET
          detect_encoding: true
          acl: public-read
          on:
            branch: master
