language: node_js
env: NODE_ENV=production
node_js:
  - "6"
  - "7"
  - "8"
script:
- npm run build
- npm run test
jobs:
  include:
    - stage: deploy
      script:
        - npm run build
      deploy:
        node_js: "6"
        provider: pages
        local_dir: dist
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        on:
          branch: master
